<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FDbIRXcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fDbIRXc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fDbIRXc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'release' => ['privates', '.errored..service_locator.fDbIRXc.App\\Entity\\Release', NULL, 'Cannot autowire service ".service_locator.fDbIRXc": it needs an instance of "App\\Entity\\Release" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'release' => 'App\\Entity\\Release',
            'entityManager' => '?',
        ]);
    }
}
