<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vu_SikyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vu.siky' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vu.siky'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'track' => ['privates', '.errored..service_locator.Vu.siky.App\\Entity\\Track', NULL, 'Cannot autowire service ".service_locator.Vu.siky": it needs an instance of "App\\Entity\\Track" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'track' => 'App\\Entity\\Track',
            'entityManager' => '?',
        ]);
    }
}
