<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IUOXIsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iUOXIs_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iUOXIs_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ArtistController::index' => ['privates', '.service_locator.aFiiVfa.App\\Controller\\ArtistController::index()', 'getArtistControllerindexService', true],
            'App\\Controller\\ArtistController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ArtistController::new()', 'getArtistControllernewService', true],
            'App\\Controller\\ArtistController::show' => ['privates', '.service_locator.e82u9tY.App\\Controller\\ArtistController::show()', 'getArtistControllershowService', true],
            'App\\Controller\\ArtistController::update' => ['privates', '.service_locator.IVi.1h5.App\\Controller\\ArtistController::update()', 'getArtistControllerupdateService', true],
            'App\\Controller\\ArtistController::delete' => ['privates', '.service_locator.IVi.1h5.App\\Controller\\ArtistController::delete()', 'getArtistControllerdeleteService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReleaseController::index' => ['privates', '.service_locator.Q3l3nAS.App\\Controller\\ReleaseController::index()', 'getReleaseControllerindexService', true],
            'App\\Controller\\ReleaseController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ReleaseController::new()', 'getReleaseControllernewService', true],
            'App\\Controller\\ReleaseController::show' => ['privates', '.service_locator.fXgAnKH.App\\Controller\\ReleaseController::show()', 'getReleaseControllershowService', true],
            'App\\Controller\\ReleaseController::edit' => ['privates', '.service_locator.fDbIRXc.App\\Controller\\ReleaseController::edit()', 'getReleaseControllereditService', true],
            'App\\Controller\\ReleaseController::delete' => ['privates', '.service_locator.fDbIRXc.App\\Controller\\ReleaseController::delete()', 'getReleaseControllerdeleteService', true],
            'App\\Controller\\ReleaseController::newTrack' => ['privates', '.service_locator.fDbIRXc.App\\Controller\\ReleaseController::newTrack()', 'getReleaseControllernewTrackService', true],
            'App\\Controller\\TrackController::index' => ['privates', '.service_locator.T6APS26.App\\Controller\\TrackController::index()', 'getTrackControllerindexService', true],
            'App\\Controller\\TrackController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\TrackController::new()', 'getTrackControllernewService', true],
            'App\\Controller\\TrackController::show' => ['privates', '.service_locator.7KVZhI8.App\\Controller\\TrackController::show()', 'getTrackControllershowService', true],
            'App\\Controller\\TrackController::edit' => ['privates', '.service_locator.Vu.siky.App\\Controller\\TrackController::edit()', 'getTrackControllereditService', true],
            'App\\Controller\\TrackController::delete' => ['privates', '.service_locator.Vu.siky.App\\Controller\\TrackController::delete()', 'getTrackControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ArtistController:index' => ['privates', '.service_locator.aFiiVfa.App\\Controller\\ArtistController::index()', 'getArtistControllerindexService', true],
            'App\\Controller\\ArtistController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ArtistController::new()', 'getArtistControllernewService', true],
            'App\\Controller\\ArtistController:show' => ['privates', '.service_locator.e82u9tY.App\\Controller\\ArtistController::show()', 'getArtistControllershowService', true],
            'App\\Controller\\ArtistController:update' => ['privates', '.service_locator.IVi.1h5.App\\Controller\\ArtistController::update()', 'getArtistControllerupdateService', true],
            'App\\Controller\\ArtistController:delete' => ['privates', '.service_locator.IVi.1h5.App\\Controller\\ArtistController::delete()', 'getArtistControllerdeleteService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReleaseController:index' => ['privates', '.service_locator.Q3l3nAS.App\\Controller\\ReleaseController::index()', 'getReleaseControllerindexService', true],
            'App\\Controller\\ReleaseController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ReleaseController::new()', 'getReleaseControllernewService', true],
            'App\\Controller\\ReleaseController:show' => ['privates', '.service_locator.fXgAnKH.App\\Controller\\ReleaseController::show()', 'getReleaseControllershowService', true],
            'App\\Controller\\ReleaseController:edit' => ['privates', '.service_locator.fDbIRXc.App\\Controller\\ReleaseController::edit()', 'getReleaseControllereditService', true],
            'App\\Controller\\ReleaseController:delete' => ['privates', '.service_locator.fDbIRXc.App\\Controller\\ReleaseController::delete()', 'getReleaseControllerdeleteService', true],
            'App\\Controller\\ReleaseController:newTrack' => ['privates', '.service_locator.fDbIRXc.App\\Controller\\ReleaseController::newTrack()', 'getReleaseControllernewTrackService', true],
            'App\\Controller\\TrackController:index' => ['privates', '.service_locator.T6APS26.App\\Controller\\TrackController::index()', 'getTrackControllerindexService', true],
            'App\\Controller\\TrackController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\TrackController::new()', 'getTrackControllernewService', true],
            'App\\Controller\\TrackController:show' => ['privates', '.service_locator.7KVZhI8.App\\Controller\\TrackController::show()', 'getTrackControllershowService', true],
            'App\\Controller\\TrackController:edit' => ['privates', '.service_locator.Vu.siky.App\\Controller\\TrackController::edit()', 'getTrackControllereditService', true],
            'App\\Controller\\TrackController:delete' => ['privates', '.service_locator.Vu.siky.App\\Controller\\TrackController::delete()', 'getTrackControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArtistController::index' => '?',
            'App\\Controller\\ArtistController::new' => '?',
            'App\\Controller\\ArtistController::show' => '?',
            'App\\Controller\\ArtistController::update' => '?',
            'App\\Controller\\ArtistController::delete' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReleaseController::index' => '?',
            'App\\Controller\\ReleaseController::new' => '?',
            'App\\Controller\\ReleaseController::show' => '?',
            'App\\Controller\\ReleaseController::edit' => '?',
            'App\\Controller\\ReleaseController::delete' => '?',
            'App\\Controller\\ReleaseController::newTrack' => '?',
            'App\\Controller\\TrackController::index' => '?',
            'App\\Controller\\TrackController::new' => '?',
            'App\\Controller\\TrackController::show' => '?',
            'App\\Controller\\TrackController::edit' => '?',
            'App\\Controller\\TrackController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArtistController:index' => '?',
            'App\\Controller\\ArtistController:new' => '?',
            'App\\Controller\\ArtistController:show' => '?',
            'App\\Controller\\ArtistController:update' => '?',
            'App\\Controller\\ArtistController:delete' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReleaseController:index' => '?',
            'App\\Controller\\ReleaseController:new' => '?',
            'App\\Controller\\ReleaseController:show' => '?',
            'App\\Controller\\ReleaseController:edit' => '?',
            'App\\Controller\\ReleaseController:delete' => '?',
            'App\\Controller\\ReleaseController:newTrack' => '?',
            'App\\Controller\\TrackController:index' => '?',
            'App\\Controller\\TrackController:new' => '?',
            'App\\Controller\\TrackController:show' => '?',
            'App\\Controller\\TrackController:edit' => '?',
            'App\\Controller\\TrackController:delete' => '?',
        ]);
    }
}
