<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e82u9tY.App\Controller\ArtistController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e82u9tY.App\\Controller\\ArtistController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'artist' => ['privates', '.errored..service_locator.e82u9tY.App\\Entity\\Artist', NULL, 'Cannot autowire service ".service_locator.e82u9tY": it needs an instance of "App\\Entity\\Artist" but this type has been excluded in "config/services.yaml".'],
        ], [
            'artist' => 'App\\Entity\\Artist',
        ]))->withContext('App\\Controller\\ArtistController::show()', $container);
    }
}
