<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IVi.1h5.App\Controller\ArtistController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IVi.1h5.App\\Controller\\ArtistController::delete()'] = ($container->privates['.service_locator.IVi.1h5'] ?? $container->load('get_ServiceLocator_IVi_1h5Service'))->withContext('App\\Controller\\ArtistController::delete()', $container);
    }
}
