<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IVi.1h5.App\Controller\ArtistController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.IVi.1h5'] ?? $container->load('get_ServiceLocator_IVi_1h5Service'));

        if (isset($container->privates['.service_locator.IVi.1h5.App\\Controller\\ArtistController::update()'])) {
            return $container->privates['.service_locator.IVi.1h5.App\\Controller\\ArtistController::update()'];
        }

        return $container->privates['.service_locator.IVi.1h5.App\\Controller\\ArtistController::update()'] = $a->withContext('App\\Controller\\ArtistController::update()', $container);
    }
}
