<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aFiiVfa.App\Controller\ArtistController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aFiiVfa.App\\Controller\\ArtistController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'artistRepository' => ['privates', 'App\\Repository\\ArtistRepository', 'getArtistRepositoryService', true],
        ], [
            'artistRepository' => 'App\\Repository\\ArtistRepository',
        ]))->withContext('App\\Controller\\ArtistController::index()', $container);
    }
}
