<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReleaseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fDbIRXc.App\Entity\Release' shared service.
     *
     * @return \App\Entity\Release
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fDbIRXc": it needs an instance of "App\\Entity\\Release" but this type has been excluded in "config/services.yaml".');
    }
}
