<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReleaseControllernewTrackService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fDbIRXc.App\Controller\ReleaseController::newTrack()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fDbIRXc.App\\Controller\\ReleaseController::newTrack()'] = ($container->privates['.service_locator.fDbIRXc'] ?? $container->load('get_ServiceLocator_FDbIRXcService'))->withContext('App\\Controller\\ReleaseController::newTrack()', $container);
    }
}
