<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReleaseControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q3l3nAS.App\Controller\ReleaseController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q3l3nAS.App\\Controller\\ReleaseController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'releaseRepository' => ['privates', 'App\\Repository\\ReleaseRepository', 'getReleaseRepositoryService', true],
        ], [
            'releaseRepository' => 'App\\Repository\\ReleaseRepository',
        ]))->withContext('App\\Controller\\ReleaseController::index()', $container);
    }
}
