<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T6APS26.App\Controller\TrackController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T6APS26.App\\Controller\\TrackController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trackRepository' => ['privates', 'App\\Repository\\TrackRepository', 'getTrackRepositoryService', true],
        ], [
            'trackRepository' => 'App\\Repository\\TrackRepository',
        ]))->withContext('App\\Controller\\TrackController::index()', $container);
    }
}
