<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7KVZhI8.App\Controller\TrackController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7KVZhI8.App\\Controller\\TrackController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'track' => ['privates', '.errored..service_locator.7KVZhI8.App\\Entity\\Track', NULL, 'Cannot autowire service ".service_locator.7KVZhI8": it needs an instance of "App\\Entity\\Track" but this type has been excluded in "config/services.yaml".'],
        ], [
            'track' => 'App\\Entity\\Track',
        ]))->withContext('App\\Controller\\TrackController::show()', $container);
    }
}
