<?php

namespace ContainerTrzo1W0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vu.siky.App\Controller\TrackController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Vu.siky'] ?? $container->load('get_ServiceLocator_Vu_SikyService'));

        if (isset($container->privates['.service_locator.Vu.siky.App\\Controller\\TrackController::edit()'])) {
            return $container->privates['.service_locator.Vu.siky.App\\Controller\\TrackController::edit()'];
        }

        return $container->privates['.service_locator.Vu.siky.App\\Controller\\TrackController::edit()'] = $a->withContext('App\\Controller\\TrackController::edit()', $container);
    }
}
