<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTrzo1W0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTrzo1W0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTrzo1W0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTrzo1W0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTrzo1W0\App_KernelDevDebugContainer([
    'container.build_hash' => 'Trzo1W0',
    'container.build_id' => 'bd946dc2',
    'container.build_time' => 1741692083,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTrzo1W0');
